export const ORGANIZATIONS_LOAD = 'ORGANIZATIONS_LOAD';
export const ORGANIZATION_SELECT = 'ORGANIZATION_SELECT';

export const REPOSITORIES_LOAD = 'REPOSITORIES_LOAD';
export const REPOSITORY_SELECT = 'REPOSITORY_SELECT';
export const REPOSITORY_UNSELECT = 'REPOSITORY_UNSELECT';

export const LOGGED_IN_USER_LOAD = 'LOGGED_IN_USER_LOAD';
export const LOGGED_IN_USER_ERROR = 'LOGGED_IN_USER_ERROR';
export const USERS_LOAD = 'USERS_LOAD';
export const USER_SELECT = 'USER_SELECT';
export const USER_UNSELECT = 'USER_UNSELECT';
